const dotenv = require('dotenv');

const result = dotenv.config();
if (result.error) {
    throw result.error
}

const TINY_SCHOLAR_PORT = parseInt(process.env.TINY_SCHOLAR_PORT);
const DELAY_WINDOW_MIN = parseInt(process.env.DELAY_WINDOW_MIN);
const DELAY_AFTER_NUMBER_OF_REQ = parseInt(process.env.DELAY_AFTER_NUMBER_OF_REQ);
const DELAY_MINUTES = parseInt(process.env.DELAY_MINUTES);

const TELEGRAM_IS_BOT_ACTIVE = (process.env.TELEGRAM_IS_BOT_ACTIVE == "true");
const TELEGRAM_SECRET_TOKEN = process.env.TELEGRAM_SECRET_TOKEN;
const TELEGRAM_ID_LIST_TO_BE_NOTIFIED = process.env.TELEGRAM_ID_LIST_TO_BE_NOTIFIED.split(' ');
const TELEGRAM_HELP_TEXT = process.env.TELEGRAM_HELP_TEXT;

const SERVE_ONLY_CACHE = (process.env.SERVE_ONLY_CACHE == "true");

module.exports = {
    TINY_SCHOLAR_PORT: TINY_SCHOLAR_PORT,
    DELAY_WINDOW_MIN: DELAY_WINDOW_MIN,
    DELAY_AFTER_NUMBER_OF_REQ: DELAY_AFTER_NUMBER_OF_REQ,
    DELAY_MINUTES: DELAY_MINUTES,

    TELEGRAM_IS_BOT_ACTIVE: TELEGRAM_IS_BOT_ACTIVE,
    TELEGRAM_SECRET_TOKEN: TELEGRAM_SECRET_TOKEN,
    TELEGRAM_ID_LIST_TO_BE_NOTIFIED: TELEGRAM_ID_LIST_TO_BE_NOTIFIED,
    TELEGRAM_HELP_TEXT: TELEGRAM_HELP_TEXT,

    SERVE_ONLY_CACHE: SERVE_ONLY_CACHE
}